name: Check for packages updates

on:
  schedule:
    - cron: '0 0 * * 0' # Every Sunday at 00:00 UTC
  workflow_dispatch:

jobs:
  check:
    name: Check for packages updates
    runs-on: macos-14
    steps:
      - run: brew tap sqlitebrowser/tap

      - name: Run the script
        env:
          ASSIGNEES: ${{ vars.ASSIGNEES }}
          GITHUB_REPO: ${{ github.repository }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: curl https://raw.githubusercontent.com/sqlitebrowser/homebrew-tap/refs/heads/main/.github/scripts/check-update.py | python3
